# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='languages',
            new_name='technologies',
        ),
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(choices=[('DS', 'Datascience'), ('CYBER', 'Cybersecurity'), ('FRONTEND', 'Frontend')], default='FRONTEND', max_length=400),
        ),
    ]
