# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0002_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['id']},
        ),
    ]
