# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0003_auto_20181221_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='postedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
